[package]
name = "lumina-types"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
bincode = { workspace = true }
blake3 = { workspace = true }
ed25519-dalek = { workspace = true }
