[package]
name = "lumina-network"
version = "0.1.0"
edition = "2021"

[dependencies]
lumina-types = { path = "../lumina-types" }
libp2p = { workspace = true }
tokio = { workspace = true }
futures = "0.3"
